/**
 * @typedef {'high' | 'medium' | 'low'} Urgency - The priority that the task should take in terms of how quickly it should be completed
 * @typedef {'recent' | 'oldest' | 'upcoming'} Sorting - One of three possible predifined ordering approaches that task can be shown in `recent`arranges based on the task that were created closest to the current date, `oldest` does the opposide, and `upcoming` arranges based on the closest due date (if no due date, it will be placed last)
 */

/** 
 * Creates a unique ID to be used in the app. Valuw is created by combining two randomised numbers with the current timestamp. The values are divided by dashes (-) in order to ensure that the value is treated as a string (and not a number).
 */

const createId = () => {};

/** 
 * @typedef {object} Task - An object representing a task to be shown to a user 
 * @prop {string} id - A unique value generated by {@link createId} used to identify a task.
 * @prop {string} title - A short user-provided description of what the task entails 
 * @prop {boolean} completed - Whether the task has been completed or not 
 * @prop {Date} created - The exact date when the task was creared in the system
 * @prop {null} due - A user specified date for when the task should be completed 
 * @prop {Urgency} urgency - A user specified idication of how important the task
 */

/**
 * @typedef {object} Filters - User configured filter values that control what the tasks are shown.
 * @prop {string} search - A freeform string of characters that is matched against a task title 
 * @prop {Urgency | 'any'} urgency - Only shows task matching the value. `any` shows all tasks.
 * @prop {Sorting} sorting - Determines the order in which task are displayed.
 */

/**
 * @typedef {object} State - All data associated with the specific instance of the app
 * @prop {Record<string, Task>} tasks - A list of all task that have been created
 * @prop {Array<string>} displaying - `id` values of the task should be shown.
 * @prop {Filters} filters - An object containing the current filter state of the tasks. 
 */

/**
 * @type {State}
 */
export const state =  { 
        tasks: {},
        displaying: [],

        filters: {
            search: "",
            sorting: "recent",
            urgency: "any"
        }
    }

